### ISSUE TITLE
Automatically Set Timezone

### ISSUE THREAD

**Issue by Lv2hack** [skx/esp8266#11]
What do you think about a function to set the timezone based on the public IP address?  Something like timezoneapi.io will return the TZ of the IP address.  Only thing it requires HTTPS.  I believe the ESP8266 can be an SSL client although I have not investigated the code.  Setting the timezone is an important feature for me to make the project more portable.  Currently, changing the TZ requires editing the code.

**Comment by skx** [comment]
I suspect that most of the users of the code here wouldn't know what their public IP is - in my own cases  I'm getting a 10.0.0.0/24 - and I'd be wary of adding too-complex code to handle automation if it resulted in being tied to a service which had bogus data.  (I'm frequently mis-identified by my IP as being in Russia for example!)

What I found useful for this was to use NTP, and allow the user to set it via the web-server.  For example you can see in my helsinki project I do that here:

* [Set the default](https://github.com/skx/esp8266/blob/master/d1-helsinki-tram-times/d1-helsinki-tram-times.ino#L160)
* [Load any altered value from flash](https://github.com/skx/esp8266/blob/master/d1-helsinki-tram-times/d1-helsinki-tram-times.ino#L256)
  * Either way [set the timezone here](https://github.com/skx/esp8266/blob/master/d1-helsinki-tram-times/d1-helsinki-tram-times.ino#L315)
* [Allow the user to change it via `http://ip/?tz=3`](https://github.com/skx/esp8266/blob/master/d1-helsinki-tram-times/d1-helsinki-tram-times.ino#L1247)

I agree this code duplication is a little bad, when it is in multiple projects, but I think the solution itself is pretty clean and portable.

**Comment by Lv2hack** [comment]
Thanks that is also a good method.  I was thinking (again to make it as simple as possible for users) that I could also use the analog input with a potentiometer to allow the user to set the TZ by rotating the knob.  This would require running timeClient.setTimeOffset(time_zone_offset * (60 * 60)) in the loop rather than just in setup.  Rotating the knob would then increase/decrease the time by 1 hour (ignoring the 30 minute TZs for now). 

Another thought I had was is there any way to capture the TZ from the initial WiFi setup page?  I know this page is built-in to the ESP8266 so it may not be modifiable.  However capturing the TZ at the same time that we set the WiFi credentials would be ideal.

Any thoughts or advice on these methods?

**Comment by skx** [comment]
That would work just fine, though I personally would always think software-fixes are simpler than dedicating an input (be it a knob, or a button, to increment it).  Using hardware means people will poke it to see what it does, and you have to lose an input and design more open-casing, etc.

You _could_ set the timezone on the wifi-setup page, if you read the documentation for the WiFiManager class you can see you can add custom fields at connection/configuration time:

* https://github.com/tzapu/WiFiManager

However the timezone will change twice a year, if you're in a country with DST / BST, so you might still want to allow it to be changed more easily.  I think using a web-browser to point to the application is fine - unless you __need__ the time to be 100% correct all the time.  (i.e. Many projects don't even expose the clock to users, so in that case it probably doesn't matter.)

**Comment by Lv2hack** [comment]
Thanks, so I have a working version now that sets the timezone and the brightness via a web browser and saves both to SPIFFS so they're persistent.  I'm using two separate files which is rather silly but I'm not very good at C++.  This will probably be ok for changing to/from DST twice a year.  If I combine that with setting the TZ in the WiFi setup page I'll be satisfied.  That way on the initial setup the user won't be required to connect twice - once for WiFi settings and then again to set the TZ.

BTW your NTP Clock project has a small bug in the name of the TM1637 brightness constants.  In the .ino sketch the comments say the brightest setting is BRIGHT_BRIGHTEST but in the TM1637.h file this constant is called BRIGHTEST.

One last question.  I've never posted any code to Github but I'd like to upload my NTP Clock with Web configuration.  Do you think this should be a fork of your NTP clock?  I'm not sure what's the best way to do this.  Thanks!

**Comment by skx** [comment]
> Thanks, so I have a working version now ...

Great.

> say the brightest setting is BRIGHT_BRIGHTEST but in the TM1637.h file this constant is called BRIGHTEST.

Fixed.  That code is inconsistent, my comment _should_ have been right!

> Do you think this should be a fork of your NTP clock? 

If you literally started with a clone of my repository, then started changing and committing it could be.  But to be honest you'd probably be better off keeping it a repo in isolation - and not linked to this one.

I have no particular strong attachment to any of the code I've written here, so if it is useful then enjoy it.  (And of course code in this repository isn't 100% mine.)
