### ISSUE TITLE
error: expected unqualified-id before '.' token

### ISSUE THREAD

**Issue by 2BECKHAM2** [skx/esp8266#12]
Hi Steve,

Thanks for the excellent project.

I've observed the below error during compilation with d1-ntp-clock.ino.

**NTPClient.cpp:1: error: expected unqualified-id before '.' token

 ../common/NTPClient.cpp

 ^
exit status 1
expected unqualified-id before '.' token**

I am using Arduino IDE 1.8.5 and observed the same with 1.6.5 as well. Your help would be greatly appreciated.

Thanks in advance.

**Comment by skx** [comment]
I'm going to guess that you're compiling this project on Windows?  

If that is the case you'll find that several files in the `d1-ntp-clock` directory aren't really present, instead they're just links to the real files beneath `common/`.

So your solution should be to delete the following files from the `d1-ntp-clock` directory:

* `NTPClient.cpp`
* `NTPClient.h`
* `WiFiManager.cpp`
* `WiFiManager.h`
* `debug.h`

Then copy those files into the directory, from their real location in the `common/` directory.

Once you've done that you can re-open the project in the arduino studio and it should just work.

I hope that helps.  If it doesn't please do let me know.

**Comment by 2BECKHAM2** [comment]
Thanks for the excellent support. It's awesome.

Many thanks again.

**Comment by 2BECKHAM2** [comment]
Thanks for the excellent support. It works like a charm now.

Many thanks again.

**Comment by skx** [comment]
No problem, I'm glad these small projects are useful to other people :)
